apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: # kpt-merge: default/netact-integration
  name: netact-integration-b
  namespace: default
  annotations:
    internal.kpt.dev/upstream-identifier: 'kustomize.toolkit.fluxcd.io|Kustomization|default|netact-integration'
spec:
  kubeConfig:
    secretRef:
      name: target-kubeconfig
  dependsOn:
  - name: workload-b
  sourceRef:
    kind: GitRepository
    name: nc-app
  path: "./network-function-new-flux-b/netact-integration/"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
  force: true
