apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helloworld-go-ms
  namespace: pkc
spec:
  interval: 1m
  chart:
    spec:
      chart: ./pkc/helmcharts/helloworld-go-1.3.51.tgz
      version: '1.3.51'
      sourceRef:
        kind: GitRepository
        name: nc-app
        namespace: pkc
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: pkc
