apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata: # kpt-merge: default/app-deploy
  name: app-deploy
  namespace: network-function-new-flux-a
  annotations:
    internal.kpt.dev/upstream-identifier: 'kustomize.toolkit.fluxcd.io|Kustomization|default|app-deploy'
spec:
  kubeConfig:
    secretRef:
      name: target-kubeconfig
  dependsOn:
  - name: app-pre-deploy
  sourceRef:
    kind: GitRepository
    name: nc-app
  path: "./network-function-new-flux-a/workload/"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
