apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-function-flux-a
  namespace: default
spec:
  interval: 15m
  path: ./network-function-flux-a/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: nc-app
