apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: default
spec:
  kubeConfig:
    secretRef:
      name: target-kubeconfig
  interval: 15m
  path: ./infra/
  prune: true
  sourceRef:
    kind: GitRepository
    name: nc-app
