apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: default
spec:
  interval: 15m
  path: ./infra/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: nc-app
