apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 3-network-function-new-flux-b
  namespace: default
spec:
  dependsOn:
  - name: 2-network-function-new-flux-a
  interval: 15m
  path: ./network-function-new-flux-b/flux
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: nc-app
