apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-function-new-flux-b
  namespace: default
spec:
  interval: 15m
  path: ./network-function-new-flux-b/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: nc-app
