apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 2-network-function-new-flux-a
  namespace: default
spec:
  dependsOn:
  - name: 1-infra
  interval: 15m
  path: ./network-function-new-flux-a/flux
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: nc-app
