apiVersion: v1
kind: Namespace

metadata:
  name: network-function-a

---

apiVersion: configsync.gke.io/v1beta1
kind: RepoSync

metadata:
  name: repo-sync # this name is required
  namespace: network-function-a

spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/spatanka10/deployments.git
    dir: /network-function-a # we expect Porch to put the kpt package here
    branch: main
    auth: none

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: ns-reconciler-network-a-function
  namespace: network-function-a

subjects:
- kind: ServiceAccount
  name: ns-reconciler-network-function-a # created by Config Sync for the RepoSync reconciler
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
