- apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata: # kpt-merge: default/app-pre-deploy
    name: app-pre-deploy
    namespace: default
    annotations:
      internal.kpt.dev/upstream-identifier: 'kustomize.toolkit.fluxcd.io|Kustomization|default|app-pre-deploy'
      config.kubernetes.io/index: '0'
      internal.config.kubernetes.io/index: '0'
      internal.config.kubernetes.io/path: 'flux/pre-deploy.yaml'
      config.kubernetes.io/path: 'flux/pre-deploy.yaml'
  spec:
    kubeConfig:
      secretRef:
        name: target-kubeconfig
    sourceRef:
      kind: GitRepository
      name: nc-app
    path: "./network-function-flux/pre-deploy/"
    interval: 60m
    timeout: 5m
    prune: true
    wait: true
    force: true
