apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: example/default
  name: default
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: '|ResourceQuota|example|default'
spec:
  hard:
    cpu: "40"
    memory: 40G
